name: Actions checkout test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Confirm checkout worked
        run: echo "Checkout OK"
